### ISSUE TITLE
Missing Geo Information

### ISSUE THREAD

**Issue by ffibk** [ffnord/ffnord-alfred-announce#16]
Hey, its possible to add geo information ? And may have you a solution to work without lsb-release
 ? on a openwrt system with a rb433 board?

**Comment by genofire** [comment]
1. You just need to create the folder `nodeinfo.d/location/` and create the files `longitude` and `latitude` with the values.
2. no, this announce script is for server systems, for openwrt look at https://github.com/freifunk-gluon/gluon

**Comment by ffibk** [comment]
Hello Geno,

my problem is i have some RB433ah for this Board is not release
availeble. At the moment i try to compile it but im not sure if that
will be work.



regards

Rolf

Am 20.06.16 um 09:03 schrieb Geno:
